# Assignment - System of Linear Equations
---
<b> Submitted by Maria Eloisa H. Garcia (ID No. 20102861, BSCS-III)
<br>

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [2]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

def BackSub(C, p):
# =============================================================================
#    Perform backward substitution to solve the upper triangular system
#
#    Parameters:
#    - C: Upper triangular matrix (n x n)
#    - p: Right-hand side vector (n)
#
#    Returns x: Solution vector
# =============================================================================

    n = C.shape[0]
    z = np.zeros(n)

    for i in range(n - 1, -1, -1):
        z[i] = p[i]
        for j in range(i + 1, n):
            z[i] -= C[i, j] * z[j]
        z[i] /= C[i, i] if C[i, i] != 0 else 1

    return z

# <font color = red> Assignment 2 </font>
---
### INSTRUCTIONS
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex
---

1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
- $cos{x}4y+z = \sqrt{3}$
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
- $x^1+y^1+z^1=0$

#### Answer:
- $\cos{\theta}x+4y+z = \sqrt{3}$ is a linear equation. It has the term $\cos{\theta}x$, which is a constant $\cos{\theta}$ multiplied by a variable $x$ raised to the first power. This form applies to the rest of the terms.
- $cos{x}4y+z = \sqrt{3}$ is not a linear equation because it has functions (such as a trigonometric function) and exponents besides 1.
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ is not a linear equation because it has functions and exponents besides 1; specifically the exponent -1 in the first term $x^{-1}$, the reciprocal of the variable $x$.
- $x^1+y^1+z^1=0$ is a special case of linear equations, specifically a homogeneous linear equation where all the variables have a coefficient of 1 and are raised to the first power.

---
2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
- $4x_1+3x_2+2x_3=1$
- $3x-6y=0$

#### Answer:
- $2x_1+3x_2 =5$ <br> 
a. We need to transform the linear equation into an augmented matrix, so let: <br>
$x_1 = x$ <br> $x_2 = s$<br> the new equation becomes: $2x+3s = 5$.<br>
b. Solving for $x$ yields $x = \frac{5-3s}{2}$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 &\bigm| & \frac{5-3s}{2} \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>
d. We can have any arbitrary value of $s$  that will satisfy $\frac{5-3s}{2}$, the arbitrary value is the solution to $x_2$. While the result from the formula $\frac{5-3s}{2}$ is the solution to $x$.

- $4x_1+3x_2+2x_3=1$<br>
a. We need to transform the linear equation into an augmented matrix, so let: <br>
$x_1 = x$ <br>
$x_2 = s$<br>
$x_3 = t$<br>
the new equation becomes: $4x+3s+2t = 1$.<br>
b. Solving for $x$ yields $x = \frac{1-3s-2t}{4}$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{1-3s-2t}{4} \\
    0 & 1 & 0 &\bigm| & s \\
    0 & 0 & 1 &\bigm| & t \\
\end{pmatrix}<br>
d. We can have any arbitrary values of $s$ and $t$ that will satisfy $\frac{1-3s-2t}{4}$, these arbitrary values are the solutions to $x_2,x_3$. While the result from the formula $\frac{1-3s-2t}{4}$ is the solution to $x$.

- $3x-6y=0$<br> 
a. We need to transform the linear equation into an augmented matrix, so let: <br>
$y = s$<br>
the new equation becomes: $3x-6s = 0$.<br>
b. Solving for $x$ yields $x = 2s$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 &\bigm| & 2s \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>
d. We can have any arbitrary value of $s$ that will satisfy $2s$, the arbitrary value is the solution to $y$. While the result from the formula $2s$ is the solution to $x$.

---
3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0
\end{equation}
\begin{equation}
2x+y = 3
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+5y= -1
\end{equation}
\begin{equation}
-x+y = -5
\end{equation}
\begin{equation}
2x+4y = 4
\end{equation}
c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1
\end{equation}
\begin{equation}
x_1+x_3 = 0
\end{equation}
\begin{equation}
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>

#### Answer:
##### a. by Elimination
\begin{align}
L_1 : x-y = 0 \\
L_2 : 2x+y = 3 \\
\end{align}
<br>
- Perform forward elimination to eliminate $y$, add $L_1$ and $L_2$: <br>
\begin{align}
L_1+ L_2 : 3x=3
\end{align}
<br>
\begin{align}
\frac{3x}{3} =\frac{3}{3}
\end{align}
<br>
\begin{align}
\therefore \ x = 1 \\
\end{align}
<br>
- Perform back substituion to get the value of $y$:<br>
\begin{align}
2x+y=3\\
\end{align}
<br>
\begin{align}
2(1)+y=3 \\
\end{align}
<br>
\begin{align}
2+y=3 \\
\end{align}
<br>
\begin{align}
y=3-2 \\
\end{align}
<br>
\begin{align}
y = 1 \\
\end{align}
<br>
\begin{align}
\therefore \ x = 1, y = 1
\end{align}
- Pythonic Solution: <br>

In [10]:
C = np.array([[1, -1],[2, 1]])
p = np.array([0, 3])
C = RowAdd(C, 0, 1, -2)
print("Step 1:")
print(C, '\n')

sol_x, sol_y = BackSub(C, p)
print("Solution: x =", sol_x, ", y =", sol_y)

Step 1:
[[ 1. -1.]
 [ 0.  3.]] 

Solution: x = 1.0 , y = 1.0


##### b. by Gaussian Elimination<br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2},\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    1 & 2 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    1 & 2 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -3 &\bigm| & 3 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -3 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{3}\text{R}_{3}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
- From the resulting augmented matrix, it can be shown that:
\begin{equation}
x+5y=-1 \\
\end{equation}
\begin{equation}
y=-1 \\
\end{equation}
- Performing back substitution, we can say that:
\begin{equation}
x+5y=-1
\leftrightarrow x+5(-1)=-1
\leftrightarrow x-5=-1
\leftrightarrow x=-1+5\
\leftrightarrow x=4\\
\end{equation}
- the solution in vector form is:
\begin{pmatrix}
    4 \\
    -1 \\
\end{pmatrix}
- Pythonic Solution:

In [55]:
C = np.array([[1, 5, -1], [-1, 1, -5], [2, 4, 4]])

# Perform row operations
C = RowAdd(C, 0, 1, 1)
print("Step 1:")
print(C, '\n')

C = RowScale(C, 1, 1/6)
print("Step 2:")
print(C, '\n')

C = RowScale(C, 2, 1/2)
print("Step 3:")
print(C, '\n')

C = RowAdd(C, 1, 2, -1)
print("Step 4:")
print(C, '\n')

C = RowScale(C, 2, -1/3)
print("Step 5:")
print(C, '\n')

C = RowAdd(C, 1, 2, -1)
print("Step 6:")
print(C, '\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_x, sol_y, sol_z = BackSub(C, p)
print("Solution: x =", sol_x, ", y =", sol_y, ", z =", sol_z)

Step 1:
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

Step 2:
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 2.  4.  4.]] 

Step 3:
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 1.  2.  2.]] 

Step 4:
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 1.  1.  3.]] 

Step 5:
[[ 1.          5.         -1.        ]
 [ 0.          1.         -1.        ]
 [-0.33333333 -0.33333333 -1.        ]] 

Step 6:
[[ 1.          5.         -1.        ]
 [ 0.          1.         -1.        ]
 [-0.33333333 -1.33333333  0.        ]] 

Solution: x = 4.0 , y = -1.0 , z = 0.0


##### c. by Gaussian Elimination<br><br>
$
\begin{pmatrix}
    2 & 3 & -1\bigm| & -1 \\
    1 & 0 & 1\bigm| & 0 \\
    -1 & 2 & -2\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    1 & 0 & 1\bigm| & 0 \\
    -1 & 2 & -2\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    1 & 0 & 1\bigm| & 0 \\
    -1 & 2 & -2\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & -\frac{3}{2}\ & \frac{3}{2}\bigm| & \frac{1}{2}\\\
    -1 & 2 & -2\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & -\frac{3}{2}\ & \frac{3}{2}\bigm| & \frac{1}{2}\\\
    -1 & 2 & -2\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & -\frac{3}{2}\ & \frac{3}{2}\bigm| & \frac{1}{2}\\\
    0 & \frac{7}{2}\ & -\frac{5}{2}\bigm| & -\frac{1}{2}\\\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & -\frac{3}{2}\ & \frac{3}{2}\bigm| & \frac{1}{2}\\\
    0 & \frac{7}{2}\ & -\frac{5}{2}\bigm| & -\frac{1}{2}\\\
\end{pmatrix}
\xrightarrow{-\frac{2}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & \frac{7}{2}\ & -\frac{5}{2}\bigm| & -\frac{1}{2}\\\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & \frac{7}{2}\ & -\frac{5}{2}\bigm| & -\frac{1}{2}\\\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & 0 & 1\bigm| & -\frac{5}{9}\\\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & \frac{3}{2}\ & -\frac{1}{2}\bigm| & -\frac{1}{2}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & 0 & 1\bigm| & -\frac{5}{9}\\\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{3}\bigm| & \frac{1}{3}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & 0 & 1\bigm| & -\frac{5}{9}\\\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & \frac{1}{3}\bigm| & \frac{1}{3}\\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & 0 & 1\bigm| & -\frac{5}{9}\\\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0\bigm| & 0\\
    0 & 1 & -1\bigm| & -\frac{1}{3}\\\
    0 & 0 & 1\bigm| & -\frac{5}{9}\\\
\end{pmatrix}
$
<br>
- From the resulting augmented matrix, it can be shown that:
\begin{equation}
x_1=0\\
\end{equation}
\begin{equation}
x_2-x_3=-\frac{1}{3}\\\
\end{equation}
\begin{equation}
x_3=-\frac{5}{9}\\\
\end{equation}
- Performing back substitution, we can say that:
\begin{equation}
x_2-x_3=-\frac{1}{3}\\\
\leftrightarrow x_2-(-\frac{5}{9})=-\frac{1}{3}\
\leftrightarrow x_2+\frac{5}{9}=-\frac{1}{3}\
\leftrightarrow x_2=-\frac{1}{3}-\frac{5}{9}\
\leftrightarrow x_2=-\frac{8}{9}\
\end{equation}
- the solution in vector form is:
\begin{pmatrix}
    0 \\
    -\frac{8}{9}\\\
    -\frac{5}{9}\\\
\end{pmatrix}
- Pythonic Solution:

In [56]:
C = np.array([[2, 3, -1, -1], [1, 0, 1, 0], [-1, 2, -2, 0]])

# Perform row operations
C = RowScale(C, 0, 1/2)
print("Step 1:")
print(C, '\n')

C = RowAdd(C, 0, 1, -1)
print("Step 2:")
print(C, '\n')

C = RowAdd(C, 0, 2, 1)
print("Step 3:")
print(C, '\n')

C = RowScale(C, 1, -2/3)
print("Step 4:")
print(C, '\n')

C = RowAdd(C, 1, 2, -7/2)
print("Step 5:")
print(C, '\n')

C = RowAdd(C, 1, 0, -3/2)
print("Step 6:")
print(C, '\n')

C = RowAdd(C, 1, 0, 1/2)
print("Step 7:")
print(C, '\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_x, sol_y, sol_z = BackSub(C, p)
print("Solution: x1 =", sol_x, ", x2 =", sol_y, ", x3 =", sol_z)

Step 1:
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

Step 2:
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]] 

Step 3:
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]] 

Step 4:
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

Step 5:
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

Step 6:
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

Step 7:
[[ 1.          0.5         0.5        -0.16666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

Solution: x1 = -0.6666666666666665 , x2 = 0.3333333333333332 , x3 = 0.6666666666666665


---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>

#### Answer:
a. **Neither** = The last leading entry is not in a column to the right of the leading entry of the previous row. <br>
b. **Row Echelon** = All nonzero rows are above the row of all zeros. Each leading entry is in a column to the right of the preceding row. Below a leading entry are all zero entries.<br>
c. **Reduced Row Echelon** = Satisfies the row echelon conditions. Additionally, for each nonzero row, the leading entry is 1 which is also the only nonzero entry in its column. <br>
d. **Row Echelon** = It satisfies the condition of any rows of all zeroes placed at the bottom. <br>
e. **Neither** = It does not satisfy the condition of any rows of all zeroes placed at the bottom. <br>
f. **Neither** = Each leading entry is not in a column to the right of the leading entry of the previous row. <br>
g. **Neither** = The second leading entry is not in a column to the right of the leading entry of the previous row.<br>
g. **Row Echelon** = All nonzero rows are above the row of all zeros. Each leading entry is in a column to the right of the preceding row. Below a leading entry are all zero entries. <br>

---
5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>
b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}
c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>
d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>

#### Answer:
##### a.
$
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    2 & -1 & -1\bigm| & 0 \\
    4 & -1 & 1\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & -5 & 5\bigm| & -18 \\
    4 & -1 & 1\bigm| & 4 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & -5 & 5\bigm| & -18 \\
    4 & -1 & 1\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & -5 & 5\bigm| & -18 \\
    0 & -9 & 13\bigm| & -32 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & -5 & 5\bigm| & -18 \\
    0 & -9 & 13\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & 1 & -1\bigm| & \frac{18}{5}\\\
    0 & -9 & 13\bigm| & -32 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & 1 & -1\bigm| & \frac{18}{5}\\\
    0 & -9 & 13\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 9\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3\bigm| & 9 \\
    0 & 1 & -1\bigm| & \frac{18}{5}\\\
    0 & 0 & 4\bigm| & -\frac{2}{5}\\\
\end{pmatrix}
$
<br>
- From the resulting augmented matrix, it can be shown that:
\begin{equation}
x_1+2x_2-3x_3=9\\
\end{equation}
\begin{equation}
x_2-(-x_3)=\frac{18}{5}\\\
\end{equation}
\begin{equation}
4x_3= - \frac{2}{5}\\
\end{equation}

- Performing back substitution, we can say that:
\begin{equation}
4x_3=-\frac{2}{5}\\
\leftrightarrow \frac{4x_3}{4} =\frac{-\frac{2}{5}}{4}\
\leftrightarrow x_3=\frac{1}{10}\
\end{equation}

\begin{equation}
x_2-x_3=\frac{18}{5}\\
\leftrightarrow x_2-(\frac{1}{10})=\frac{18}{5}\
\leftrightarrow x_2-\frac{1}{10}=\frac{18}{5}\
\leftrightarrow x_2=\frac{18}{5}+\frac{1}{10}\
\leftrightarrow x_2=\frac{37}{10}\
\end{equation}

\begin{equation}
x_1+2x_2-3x_3=9\\
\leftrightarrow x_1+2(\frac{37}{10})-3(\frac{1}{10})=9\\
\leftrightarrow x_1+\frac{37}{5}-\frac{3}{10}=9\\
\leftrightarrow x_1=9-\frac{37}{5}+\frac{3}{10}
\leftrightarrow x_1=\frac{19}{10}\\
\end{equation}

- the solution in vector form is:
\begin{pmatrix}
    \frac{19}{10}\\\
    \frac{37}{10}\\\
    \frac{1}{10}\\\
\end{pmatrix}
- Pythonic Solution:

In [10]:
C = np.array([[1, 2, -3, 9], [2, -1, -1, 0], [4, -1, 1, 4]])

# Perform row operations
C = RowAdd(C, 0, 1, -2)
print("Step 1:")
print(C,'\n')

C = RowAdd(C, 0, 2, -4)
print("Step 2:")
print(C,'\n')

C = RowScale(C, 1, -1/5)
print("Step 3:")
print(C,'\n')

C = RowAdd(C, 1, 2, 9)
print("Step 4:")
print(C,'\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_x, sol_y, sol_z = BackSub(C[:, :-1], p)
print("Solution: x1 =", sol_x, ", x2 =", sol_y, ", x3 =", sol_z)

Step 1:
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

Step 2:
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

Step 3:
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

Step 4:
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

Solution: x1 = 1.8999999999999995 , x2 = 3.6999999999999997 , x3 = 0.09999999999999964


##### b.
$
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    2 & 1 & 1\bigm| & 1 \\
    -1 & 1 & -1\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    0 & -3 & 1\bigm| & 3 \\
    -1 & 1 & -1\bigm| & -1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    0 & -3 & 1\bigm| & 3 \\
    -1 & 1 & -1\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    0 & -3 & 1\bigm| & 3 \\
    0 & 3 & -1\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    0 & -3 & 1\bigm| & 3 \\
    0 & 3 & -1\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0\bigm| & -1 \\
    0 & -3 & 1\bigm| & 3 \\
    0 & 0 & 0\bigm| & 1 \\
\end{pmatrix}
$
<br>
- From the resulting augmented matrix, the last row indicates an inconsistent system:
\begin{equation}
0x + 0y + 0z = 1\\
\end{equation}
Thus, there is no solution to this system.
<br>
- Pythonic Solution:

In [15]:
C = np.array([[1, 2, 0, -1], [2, 1, 1, 1], [-1, 1, -1, -1]])

# Perform row operations
C = RowAdd(C, 0, 1, -2)
print("Step 1:")
print(C,'\n')

C = RowAdd(C, 0, 2, 1)
print("Step 2:")
print(C,'\n')

C = RowAdd(C, 1, 2, 1)
print("Step 3:")
print(C,'\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_x, sol_y, sol_z = BackSub(C[:, :-1], p)
print("Solution: x1 =", sol_x, ", x2 =", sol_y, ", x3 =", sol_z)
print("Inconsistent system due to Row 3: 0x + 0y + 0z does not equate to 1")

Step 1:
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

Step 2:
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

Step 3:
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  0.  0.  1.]] 

Solution: x1 = 0.33333333333333326 , x2 = -0.6666666666666666 , x3 = 1.0
Inconsistent system due to Row 3: 0x + 0y + 0z does not equate to 1


##### c.
$
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    -1 & 2 & 1\bigm| & 0 \\
    2 & 4 & 6\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    0 & -1 & -1\bigm| & 0 \\
    2 & 4 & 6\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    0 & -1 & -1\bigm| & 0 \\
    2 & 4 & 6\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    0 & -1 & -1\bigm| & 0 \\
    0 & 10 & 10\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    0 & -1 & -1\bigm| & 0 \\
    0 & 10 & 10\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2\bigm| & 0 \\
    0 & -1 & -1\bigm| & 0 \\
    0 & 0 & 0\bigm| & 0 \\
\end{pmatrix}
$
<br>
- From the second equation, we can express \(y\) as \(z\): \(y = -z\).
Then we substitute \(y\) back into the first equation:
\[ x - 3(-z) - 2z = 0 \]
After simplifying, we have \(x = -z\).
We can observe that the solution to the system is \(x = -z\), \(y = -z\), where \(z\) is a free variable.
Thus, the system has infinitely many solutions and can be written in parametric form as:
\[ \begin{align*}
x &= -z \\
y &= -z \\
z & \text{ is any real number} \\
\end{align*} \]
- Pythonic Solution:

In [13]:
C = np.array([[1, -3, -2, 0], [-1, 2, 1, 0], [2, 4, 6, 0]])

# Perform row operations
C = RowAdd(C, 0, 1, 1)
print("Step 1:")
print(C,'\n')

C = RowAdd(C, 0, 2, -2)
print("Step 2:")
print(C,'\n')

C = RowAdd(C, 1, 2, 10)
print("Step 3:")
print(C,'\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_x, sol_y, sol_z = BackSub(C[:, :-1], p)
print("Solution: x1 =", sol_x, ", x2 =", sol_y, ", x3 =", sol_z)
print("The system has infinitely many solutions.")

Step 1:
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

Step 2:
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

Step 3:
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

Solution: x1 = 0.0 , x2 = -0.0 , x3 = 0.0
The system has infinitely many solutions.


##### d.
$
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    1 & -1 & -1 & 1 &\bigm| &  0 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    1 &  1 &  0 & 1 &\bigm| &  2 \\
\end{pmatrix}
\xrightarrow{\text{R}_4 - \text{R}_1}
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    1 & -1 & -1 & 1 &\bigm| &  0 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    1 & -1 & -1 & 1 &\bigm| &  0 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
\xrightarrow{\text{R}_2 - \text{R}_1}
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
\xrightarrow{\text{R}_2 + 2 \text{R}_3}
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 &  0 & -1 & 0 &\bigm| &  1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1\bigm| & 1 \\
    0 & 0 & -1 & 0\bigm| & 1 \\
    0 & 1 & 1 & 0\bigm| & 1 \\
    0 & 0 & -2 & 0\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_2 \leftrightarrow \text{R}_3}
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -1 & 0 &\bigm| &  1 \\
    0 &  0 & -2 & 0 &\bigm| &  1 \\
\end{pmatrix}
\xrightarrow{\text{R}_4 - 2 \text{R}_3}
\begin{pmatrix}
    1 &  1 &  2 & 1 &\bigm| &  1 \\
    0 &  1 &  1 & 0 &\bigm| &  1 \\
    0 &  0 & -1 & 0 &\bigm| &  1 \\
    0 &  0 &  0 & 0 &\bigm| & -1 \\
\end{pmatrix}
$
<br>
- From the resulting augmented matrix, the last row indicates an inconsistent system:
\begin{equation}
0w + 0x + 0y + 0z = -1\\
\end{equation}
Thus, there is no solution to this system.
<br>
- Pythonic Solution:

In [8]:
C = np.array([[1, 1, 2, 1, 1], [1, -1, -1, 1, 0], [0, 1, 1, 0, 1], [1, 1, 0, 1, 2]])

# Perform row operations
C = RowAdd(C, 0, 3, -1)
print("Step 1:")
print(C,'\n')

C = RowAdd(C, 0, 1, -1)
print("Step 2:")
print(C,'\n')

C = RowAdd(C, 2, 1, 2)
print("Step 3:")
print(C,'\n')

C = RowSwap(C, 1, 2)
print("Step 4:")
print(C,'\n')

C = RowAdd(C, 2, 3, -2)
print("Step 5:")
print(C,'\n')

# Extract p vector
p = C[:, -1]

# Perform backward substitution
sol_w, sol_x, sol_y, sol_z = BackSub(C[:, :-1], p)
print("Solution: w =", sol_z, ", x =", sol_w, ", y =", sol_x, ", z =",sol_y )
print("Inconsistent system due to Row 4: 0w + 0x + 0y + 0z does not equate to -1")

Step 1:
[[ 1.  1.  2.  1.  1.]
 [ 1. -1. -1.  1.  0.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

Step 2:
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

Step 3:
[[ 1.  1.  2.  1.  1.]
 [ 0.  0. -1.  0.  1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

Step 4:
[[ 1.  1.  2.  1.  1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

Step 5:
[[ 1.  1.  2.  1.  1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -1.  0.  1.]
 [ 0.  0.  0.  0. -1.]] 

Solution: w = -1.0 , x = 2.0 , y = 2.0 , z = -1.0
Inconsistent system due to Row 4: 0w + 0x + 0y + 0z does not equate to -1


---
6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br><br>
b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>

#### Answer:
##### a.
1. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
<br>
$ \begin{bmatrix} -1 \\ 3 \end{bmatrix} y + \begin{bmatrix} 2 \\ -6 \end{bmatrix} z = \begin{bmatrix} 1 \\ 2 \end{bmatrix} 
$ <br>
<br>
2. We want to solve the system of linear equations:<br>
\begin{equation}
-y+2z=1
\end{equation}
\begin{equation}
3y-6z=2
\end{equation}<br>
3. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1}}
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    0 & 0 &\bigm| & 5 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    0 & 0 &\bigm| & 5 \\
\end{pmatrix}
\xrightarrow{-1\text{R}_{1}, \frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & -2 &\bigm| & -1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$<br>
<br>
4. An inconsistent system of linear equations is observed since $0\neq1$.  $\therefore$ The vectors are not a linear combination of each other.

##### b.
1. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
<br>
$ \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} y + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} z = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} 
$ <br>
<br>
2. We want to solve the system of linear equations:<br>
\begin{equation}
y=1
\end{equation}
\begin{equation}
y+z=2
\end{equation}
\begin{equation}
z=3
\end{equation}<br>
3. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    1 & 1 &\bigm| & 2 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}, \frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
5. An inconsistent system of linear equations is observed since $0\neq1$.  $\therefore$ The vectors are not a linear combination of each other.

##### c.
1. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
<br>
$ \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} y + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} z = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} 
$ <br>
<br>
2. We want to solve the system of linear equations:<br>
\begin{equation}
y=3
\end{equation}
\begin{equation}
y+z=1
\end{equation}
\begin{equation}
z=-2
\end{equation}<br>
3. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    1 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
$
<br>
<br>
4. We can say that $y=3$ and $z=-2$, and the linear combination is $3u_2-2u_3=v$.<br>
<br>
5. $\therefore$ The vectors are linear combinations of each other.

---
7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>

#### Answer:
#### a.
1. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ -1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \end{bmatrix} \\
\end{equation}
2. Transform the linear equation into its reduced row echelon form:
<br>
<br>
$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    1 & -1 &\bigm| & b \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & -2 &\bigm| & b-a \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & -2 &\bigm| & b-a \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & -1 &\bigm| & b \\
    0 & -2 &\bigm| & b-a \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & b \\
    0 & -2 &\bigm| & b-a \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2} \text{R}_{2}}
\begin{pmatrix}
    1 & -1 &\bigm| & b \\
    0 & 1 &\bigm| & -\frac{b+a}{2} \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & b \\
    0 & 1 &\bigm| & -\frac{b+a}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & b \\
    0 & 1 &\bigm| & \frac{b+a}{2} \\
\end{pmatrix}
$
<br><br>
3. We can say that $x=b$ and $y=\frac{b+a}{2}$.
4. $\therefore$ The vectors are a span.

#### b.
1. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \ +
    \textbf{z}\begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
\end{equation}
3. Transform the linear equation into its reduced row echelon form:
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 0 &\bigm| & a-c \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
4. We can say that $x=c$, $y=a-c$ and $z=-a+b+c$.
5. $\therefore$ The vectors are a span.

#### c.
1. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \ +
    \textbf{z}\begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
\end{equation}
3. Transform the linear equation into its reduced row echelon form:
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & c \\
    0 & 1 & 0 &\bigm| & a-c \\
    0 & 0 & 1 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br><br>
4. We can say that $x=c$, $y=a-c$ and $z=-a+b+c$.
5. $\therefore$ The vectors are a span.

---
8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}

#### Answer:
a. Given the number of columns $m=4$ and the number of rows $n=4$, we can say: $4=4$. By not satisfying condition 4: $m > n$, hence we can say that the vectors are linearly independent. <br>
b. Given the number of columns $m=4$ and the number of rows $n=4$, we can say: $4=4$. By not satisfying condition 4: $m > n$, hence we can say that the vectors are linearly independent. <br>
c. Given the number of columns $m=4$ and the number of rows $n=4$, we can say: $4=4$. By not satisfying condition 4: $m > n$, hence we can say that the vectors are linearly independent. <br>